name: Build linux image

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  build-linux:
    runs-on:
      - Linux
      - self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build
      uses: docker/build-push-action@v6
      with:
        context: ./linux
        push: false
