name: Build linux image

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  build-linux:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: lowercase github.repository
      run: |
        echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
    - name: Build
      uses: docker/build-push-action@v6
      with:
        context: ./linux
        push: false
        tags: ${{ env.IMAGE_NAME }}:ubuntu
        outputs: type=docker,dest=/tmp/image_ubuntu.tar
    - name: Upload image artifact
      uses: actions/upload-artifact@v4
      with:
        name: image_ubuntu
        path: /tmp/image_ubuntu.tar
