name: Build linux image

on:
  workflow_call:
    inputs:
      upload:
        type: boolean
        required: false
        default: false

defaults:
  run:
    shell: bash

jobs:
  build-linux:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v3
    - name: lowercase github.repository
      run: |
        echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
    - name: Build
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:ubuntu ./linux
    - name: Export
      if: ${{ inputs.upload == true }}
      run: |
        docker save -o /tmp/image_ubuntu.tar ${{ env.IMAGE_NAME }}:ubuntu
    - name: Upload image artifact
      if: ${{ inputs.upload == true }}
      uses: actions/upload-artifact@v4
      with:
        name: image_ubuntu
        path: /tmp/image_ubuntu.tar
