name: Release tagged linux image

on: [workflow_dispatch]

env:
  CURRENT_VERSION: 0.1.4

defaults:
  run:
    shell: bash

jobs:
  build-linux:
    uses: ./.github/workflows/define-build-linux-image.yml
    secrets: inherit

  tag:
    runs-on: self-hosted
    steps:
    - uses: mukunku/tag-exists-action@v1.6.0
      id: check-tag
      with: 
        tag: ${{ env.CURRENT_VERSION }}
    - name: Fail if tag exists
      if: steps.check-tag.outputs.exists == 'true' 
      run: |
        echo "Tag ${{ env.CURRENT_VERSION }} exists!"
        exit 1
    - name: Print tag if it doesn't exist
      if: steps.check-tag.outputs.exists == 'false' 
      run: |
        echo "Tag ${{ env.CURRENT_VERSION }} doesn't yet exist and can be created"

  push-linux:
    needs: [tag, build-linux]
    runs-on: [self-hosted, linux]
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: lowercase github.repository
      run: |
        echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./linux
        push: true
        tags: |
          ghcr.io/${{ env.IMAGE_NAME }}:${{ env.CURRENT_VERSION }}-ubuntu

  release:
    needs: [tag, build-linux, push-linux]
    runs-on: [self-hosted, linux]
    permissions:
      contents: write
    steps:
    - name: Add body.md
      run: |
        touch body.md
    - name: Create new release
      uses: ncipollo/release-action@v1
      with:
        bodyFile: "body.md"
        tag: "${{ env.CURRENT_VERSION }}"
        commit: "main"
        token: ${{ secrets.GITHUB_TOKEN }}
