name: Build images

on: 
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    uses: ./.github/workflows/define-build-linux-image.yml
    secrets: inherit

  cleanup:
    needs: [build-linux]
    runs-on: [self-hosted, linux]
    steps:
    - name: Remove cached docker image
      if: always()
      run: |
        curl -X DELETE http://192.168.0.145:25000/attachments/gha-runner/1/image_ubuntu.tar
